const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257
    },
    events: [
        {
            created: 1582647410000,
            duration: 7200000,
            id: '268979993',
            name: 'SRE Republic - Munich',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1588784400000,
            local_date: '2020-05-06',
            local_time: '19:00',
            updated: 1582647410000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 46,
            venue: {
                id: 26055921,
                name: 'Personio GmbH',
                lat: 48.14337921142578,
                lon: 11.555990219116211,
                repinned: false,
                address_1: 'Rundfunkplatz 4',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1547827354000,
                name: 'SRE Republic',
                id: 30954885,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'SRE-Republic',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/SRE-Republic/events/268979993/',
            description: '<p>This will be our fourth meetup in the city of Munich and is certain to be another evening of interesting talks around all things SRE, as well as a fantastic opportunity to network with your peers.</p> <p>Date: Wednesday 6th May 2020<br/>Time: 6:30 PM - 9:30 PM<br/>Location: Personio GmbH, Rundfunkplatz 4, 80335 München</p> <p>Doors open for networking @ 6:30</p> <p>Session 1 @ 7:00<br/>Filip Petkovski, Senior Engineer and Pierre Piriou, Senior SRE at Personio<br/>Topic: Enabling Safer Deployments with Gitlab<br/>At Personio, we heavily rely on Gitlab. With the migration to Gitlab, we successfully solved several challenges within our infrastructure. This was essential for Personio and it\'s fast-growing pace.</p> <p>Session 2 @ 7:30<br/>To be revealed...</p> <p>Session 3 @ 8:00<br/>To be revealed...</p> <p>More networking and refreshments @ 8:30 - 9:30</p> <p>Looking forward to seeing you there!</p> ',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1579507148000,
            duration: 10800000,
            id: '268054328',
            name: 'Flutter Stammtisch',
            rsvp_limit: 40,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585245600000,
            local_date: '2020-03-26',
            local_time: '19:00',
            updated: 1583309014000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 22,
            venue: {
                id: 26348691,
                name: 'Augustiner-Keller',
                lat: 48.143524169921875,
                lon: 11.551462173461914,
                repinned: true,
                address_1: 'Arnulfstraße 52',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1543101111000,
                name: 'Flutter Munich',
                id: 30587470,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Flutter-Munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Flutter-Munich/events/268054328/',
            description: '<p>😄 At this event, there\'ll be no coding, presentations. If you want to participate at a coding night, hackathons, app demos or want to listen to tech presentations, we have many-many upcoming events, so register now <p>⭐ Let\'s meet for a drink at Augustiner-Keller!</p> <p>🎉 This event is focussing on socializing, hanging out and having a drink together. No prior Flutter experience is required 👻</p> <p>💬 We can talk about basically anything, Flutter, Dart, software, mobile development, companies, hacks, issues, other frameworks, patterns we discovered, things we want to learn next or just life in general. Just a couple of hours with fellow software developers (or people who are interested in becoming one or working in similar or related areas).</p> <p>💰 Please be aware that this event is not sponsored or hosted by a company, so there will be no free drinks or dinner. Everything you want to consume will have to be paid by you.</p> <p>🧃 Feel free to buy any beverages or meals, the restaurant has non-alcoholic beverages, and vegetarian meals, too.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1583491357000,
            duration: 7200000,
            id: '269230270',
            name: '112. JUG-München Treffen',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583946000000,
            local_date: '2020-03-11',
            local_time: '18:00',
            updated: 1583491516000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 25942014,
                name: 'Wirtshaus zum Isartal',
                lat: 48.112571716308594,
                lon: 11.553250312805176,
                repinned: true,
                address_1: 'Brudermühlstrasse 2',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1537211427000,
                name: 'Joomla User Group München',
                id: 29852639,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Joomla-User-Group-Munchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Joomla-User-Group-Munchen/events/269230270/',
            description: '<p>Komm zum JUG-München Treffen!</p> <p>Thema des Abends: </p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen<br/>- tausche Dich in lockerer Umgebung beim Stammtisch mit Gleichgesinnten aus<br/>- erhalte Hilfe zur Selbsthilfe und stelle Fragen an andere User und Profis<br/>- höre Dir Vorträge über und rund um Joomla! an oder halte selbst welche<br/>- nimm an Workshops teil oder vielleicht magst Du selbst einen veranstalten?<br/>- teile Dein Wissen und Deine Erfahrungen mit Joomla! oder Erweiterungen<br/>- erfahre aktuelle Informationen aus erster Hand rund um Joomla! oder Joomla!-Events<br/>- profitiere von unseren tollen Lokations und melde Dich heute noch zum Treffen an</p> ',
            how_to_find_us: 'Nebenraum',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1576845461000,
            duration: 7200000,
            id: '267317596',
            name: 'Pitch Club Developer Edition #47',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1584039600000,
            local_date: '2020-03-12',
            local_time: '20:00',
            updated: 1583498967000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 5,
            venue: {
                id: 25959917,
                name: 'Bar Ludwig II',
                lat: 48.12186813354492,
                lon: 11.58230972290039,
                repinned: true,
                address_1: 'Hochstraße 77',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1539021073000,
                name: 'Pitch Club Developer Edition München',
                id: 30141555,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Pitch-Club-Developer-Edition-Munchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/267317596/',
            description: '<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 12. März 2020 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #47” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter:</p> <p>Wenn Du Interesse hast, an der anschließenden Afterwork ab 20 Uhr teilzunehmen, dann melde Dich einfach auf unserer Homepage unter</p> <p>Pitch Club is looking for Software Developers and IT-Professionals for its upcoming event “Pitch Club Developer Edition #47” on March 12th, 2020, starting at 5 p.m. at Bar Ludwig II (Hochstraße 77, 81541 Munich) in Munich.</p> <p>So this is like a job interview - but reversed! Companies and startups pitch themselves, the HR concepts, jobs and projects they offer to the audience, i.e. the Software Developers and IT-Professionals, who ask tough and hair-raising questions in addition. After the pitches you can get more information in 1-on-1 talks with the companies. All participants are invited to snacks, drinks and maybe you get to know your future employer. After the official part ends at 8 p.m., the event shifts over to the Afterwork Party, accessible for everyone.</p> <p>The participation for the official part as well as catering (including snacks, soft drinks, beverages &amp; long drinks) are for free! If you want to participate at the invite-only event, starting at 5 p.m., please apply via</p> <p>Please note: Most pitches will be held in German. Nonetheless, English-speaking developers are welcomed, too!</p></p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1583338894000,
            duration: 32400000,
            id: '269183261',
            name: 'Deploy AI - Community Day',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583823600000,
            local_date: '2020-03-10',
            local_time: '08:00',
            updated: 1583338894000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 21,
            group: {
                created: 1400181332000,
                name: 'Big Data Developers in Munich',
                id: 14476282,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Big-Data-Developers-in-Munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/269183261/',
            description: '<p>REGISTER HERE FOR THIS FREE EVENT: ',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1579515441000,
            duration: 374400000,
            id: '268055581',
            name: 'Kostenloser Praxiskurs Agile Software Engineering mit der ASE Student Edition*',
            rsvp_limit: 10,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1584950400000,
            local_date: '2020-03-23',
            local_time: '09:00',
            updated: 1579515715000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 25713547,
                name: 'andrena objects Ag',
                lat: 48.12970733642578,
                lon: 11.538801193237305,
                repinned: true,
                address_1: 'Ganghoferstrasse 70',
                address_2: '5. Stock',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1460726995000,
                name: 'ASE Student Edition München',
                id: 19843628,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'ase-student-edition-muenchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/ase-student-edition-muenchen/events/268055581/',
            description: '<p>Gewinne Praxiserfahrung in Agile Software Engineering und profitiere von ',
            how_to_find_us: 'andrena objects | Office München U-Bahn Schwanthaler Höhe  | Medienfabrik Ganghoferstrasse 70 | 5. OG',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1562151747000,
            duration: 169200000,
            id: '262837309',
            name: 'Campus Hackathon München 2020',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1587142800000,
            local_date: '2020-04-17',
            local_time: '19:00',
            updated: 1562151747000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 14,
            group: {
                created: 1501244830000,
                name: 'Tech_Hub München',
                id: 25186228,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Tech_Hub-Munchen',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Tech_Hub-Munchen/events/262837309/',
            description: '<p>At Campus Hackathon coders, creative developers and designers are working together intensively and under time-pressure hands-on projects. You have 24 hours to convert an idea into code. You already have some ideas? You want to use the tools and platforms you’re familiar with? ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579193914000,
            duration: 7200000,
            id: '267965648',
            name: 'World Retro Day 2020 @ Agile Munich',
            rsvp_limit: 70,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585157400000,
            local_date: '2020-03-25',
            local_time: '18:30',
            rsvp_open_offset: 'PT432H',
            updated: 1583349113000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 8,
            venue: {
                id: 26171276,
                name: 'zooplus AG',
                lat: 48.134639739990234,
                lon: 11.566325187683105,
                repinned: true,
                address_1: 'Sonnenstr. 31, 80331 ',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1397242023000,
                name: 'Agile Munich',
                id: 13860382,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'AgileMunich',
                who: 'Agile Practitioners',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/AgileMunich/events/267965648/',
            description: '<p>Following your positive feedback from last year, we\'re bringing you the World Retro Day back this year too.</p> <p>Let\'s celebrate the World Retrospective Day with the Agile Munich community! World Retrospective Day is a volunteer-based, globally coordinated effort to share in the power of retrospectives.<br/>Retrospectives are not just an essential part of the Scrum framework, they are a fundamental practice for any group of people willing to learn from past experiences. It\'s hard to overestimate the inspiration that can be drawn from pausing to look back, reflecting on what happened and what was possible, and drawing conclusions for the future.<br/>After the encouraging feedback from last year’s participants, we look forward to welcoming members of the community for another workshop style-event. Details will be added closer to the event.</p> <p>We\'d like to thank Ilja Vishnevski from Zooplus AG for the initiative to run and facilitate this workshop. Please note that space is limited to max 50 attendees.</p> <p>Stay tuned for further details.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581873889000,
            duration: 10800000,
            id: '268754701',
            name: 'Learning how to learn in a mob',
            rsvp_limit: 12,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1584036000000,
            local_date: '2020-03-12',
            local_time: '19:00',
            updated: 1581932787000,
            utc_offset: 3600000,
            waitlist_count: 38,
            yes_rsvp_count: 21,
            venue: {
                id: 26607320,
                name: 'Mercateo',
                lat: 48.13730239868164,
                lon: 11.572970390319824,
                repinned: true,
                address_1: 'Fürstenfelder Str. 5',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1411685347000,
                name: 'Munich Software Craft Community',
                id: 17214922,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'munich-software-craft-community',
                who: 'Software Crafters',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/munich-software-craft-community/events/268754701/',
            description: '<p>Mob programming, mob testing, or generally mobbing is a wonderful approach to uncover implicit knowledge and learn from each other. It’s “all the brilliant people, working on the same thing, at the same time, in the same space, and at the same computer“. But what if you introduce a new technology no one in the mob had worked with before? What if you suddenly need knowledge in the team that nobody has? Does mobbing still prove to be an efficient way of learning in that case? Join this experiment and learn something nobody in the mob has done before. Let’s see how far we get in mastering a new skill together!</p> <p>Key takeaways:<br/>- Learn the basics of the mob approach and practice them hands-on<br/>- Experience the benefits of uncovering and sharing implicit knowledge to help everyone learn<br/>- See how having all brains in helps to solve unknown challenges and to get the best out of everybody</p> <p>This session is addressed to software craft people who want to organize mob programming at work. It is lead by Lisi Hocke who extensively practiced mob programming with her team and can share with us her experiences and insights.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1583443133000,
            duration: 10800000,
            id: '269216007',
            name: 'Track 2: Machine-Un-Learning: Von digitaler Demenz und kontrolliertem Vergessen',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585155600000,
            local_date: '2020-03-25',
            local_time: '18:00',
            updated: 1583496338000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            group: {
                created: 1439279741000,
                name: 'OC|Expert Camp München',
                id: 18822202,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'OC-Expert-Camp-Munchen',
                who: 'Begeisterte Entwickler',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/OC-Expert-Camp-Munchen/events/269216007/',
            member_pay_fee: false
        }
    ]
};

export { mockEvents };