const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257
    },
    events: [
        {
            created: 1581676443000,
            duration: 5400000,
            id: '268705764',
            name: 'Running Kubernetes on Azure',
            rsvp_limit: 80,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583429400000,
            local_date: '2020-03-05',
            local_time: '18:30',
            updated: 1581927279000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 36,
            venue: {
                id: 25766821,
                name: 'medialesson - Büro München',
                lat: 48.153099060058594,
                lon: 11.583580017089844,
                repinned: true,
                address_1: 'Leopoldstr. 8-10',
                address_2: 'c/o Nutrion Coworking Space',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1520252901000,
                name: 'Software, Technology & Design Meetup München',
                id: 27731423,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Software-Technology-Meetup-Munchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Software-Technology-Meetup-Munchen/events/268705764/',
            description: 'In this session Mohit Chhabra will give you insights how to run real apps on the most popular container orchestrator in Azure. We’ll review a high-level overview of the Azure Kubernetes Service (AKS) service and Azure Container Registry (ACR). We will start with the basic concepts of Kubernetes followed by understanding how AKS is different from the vanilla Kubernetes. Finally we\'ll be setting up and deploying a real world app on AKS. Feel free to follow along! Our speaker Mohit is working as Software Engineer at medialesson GmbH, Germany. He is currently Microsoft Most Valuable Professional for Microsoft Azure and former leader of BDotnet (India\'s Biggest offline community). He has delivered more than 50 sessions in the community and international conferences. Prior to this, Mohit was Microsoft Student Partner and Mozilla Student Representative. He was also India\'s first Azure Champion and the first person to intern in Microsoft Technology Center. This meetup will be hosted by medialesson, food and drinks will be provided. The session language is English. Please make sure you update your RSVP status 24h in advance so we don\'t waste any food!',
            how_to_find_us: 'The entry to building No. 8 is directly accessible from Leopoldstr. near Siegestor, walk down the broad spiral stairs down to the basement and enter trough the first glass door on the right hand.',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581605836000,
            duration: 9000000,
            id: '268682611',
            name: 'TW presents: Lean backends using functional Kotlin',
            rsvp_limit: 140,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583429400000,
            local_date: '2020-03-05',
            local_time: '18:30',
            updated: 1581606039000,
            utc_offset: 3600000,
            waitlist_count: 3,
            yes_rsvp_count: 140,
            venue: {
                id: 25852478,
                name: 'ThoughtWorks Munich ',
                lat: 48.135501861572266,
                lon: 11.613557815551758,
                repinned: true,
                address_1: 'Bothestraße 11',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1413448074000,
                name: 'ThoughtWorks Munich',
                id: 17658472,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'ThoughtWorks-Muenchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/268682611/',
            description: 'Join us for our first meetup in March with our colleagues Srishti and Mario! In this talk we are going to talk about building lean backends in Kotlin, using a functional approach. The language is well suited for this, as it is pragmatic, not afraid of borrowing ideas and has a burgeoning ecosystem. Many talks focus on Android development, but we want to go in the other direction and speak about server side code. Specifically, our focus will be on small services that interact with other services using REST APIs and JSON, in a microservices ecosystem. Kotlin is already quite functional, supporting things like immutability and null safety out of the box. Starting from there we will expand on these and other patterns, like avoiding exceptions and expressing logic as a sequence of transformations, with the help of the excellent Arrow library. We will show code that runs in our production applications that is both elegant and maintainable. You will be able to adopt some of our ideas incrementally and see the benefits for yourself. ABOUT SRISHTI:Srishti is a software developer and tech enthusiast. She is passionate about clean code, problem-solving, test-driven development, and constantly learning topics that help her to develop quality software. ABOUT MARIO:Mario develops software for a living. Then he goes home and continues reading about software because he just cannot get enough.At some point, somebody thought it was a good idea to make him the technical lead of an agile team. He quickly discovered that building things himself is not the same as helping somebody else figure it out.He learned, somewhat to his surprise, that he really enjoys sharing ideas. According to their feedback, other developers have managed to learn something from Mario. At least they don\'t tend to run away screaming, which is, as he thinks, a good thing. SNACKS:As always we are offering various snacks and, beer and soft drinks. No full meal, but something to nibble on. AGENDA:18:30 Doors open for snacks, drinks and mingle19:00 Talk and questions20:00 More questions, drinks and mingle ',
            how_to_find_us: 'The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581930400000,
            duration: 12600000,
            id: '268770204',
            name: 'Find the common language between business and IT (with Zsófia Herendi)',
            rsvp_limit: 60,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583946000000,
            local_date: '2020-03-11',
            local_time: '18:00',
            updated: 1582043298000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 40,
            group: {
                created: 1510734921000,
                name: 'DDD MUC',
                id: 26604821,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'DDD-MUC',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/DDD-MUC/events/268770204/',
            description: 'IMPORTANT:We\'re still checking who can host this event, so there will be updates! --- Zsófia Herendi, IBM Zsófia is a product manager who has spent more than 14 years bringing developers and business people together, 10+ years working on different teams and 6+ years working in an agile environment. She is a skilled modeler with a passion for diagramming and an addiction to optimizing flow. --- Find the common language between business and IT Did you know that there are large corporates out there with hundreds of customised versions of the same ERP system built by different teams serving the same purpose? Or, have you observed shadow IT, where business departments take matters into their own hands when not getting attention in the IT department?Complex legacy architecture all too often reduce the competitive edge and business agility in large organisations, as well as becoming both more costly to maintain and expand upon. Resolving service problems takes a long time and new initiatives to fix and improve takes too long to realise, if at all.Value stream mapping and business process diagrams may provide some insight, but they will not necessarily give you the proper context as duplications and bias in your ecosystem often is well hidden. You lack the necessary situational awareness.When walking out of this session you will have the tools needed to gain a holistic view of your company, including the ability to map out IT’s current situation. ',
            visibility: 'public',
            member_pay_fee: false
        }
    ]
};

export { mockEvents };